### ISSUE TITLE
Can't install robotframework-snmplibrary using pip

### ISSUE THREAD

**Issue by urtow** [kontron/robotframework-snmplibrary#3]
OS: Ubuntu 16.04 amd64

` pip install robotframework-snmplibrary
Collecting robotframework-snmplibrary
  Using cached robotframework-snmplibrary-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-32rei521/robotframework-snmplibrary/setup.py", line 44
        print "build_libdoc requires the Robot Framework package."
                                                                 ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-32rei521/robotframework-snmplibrary/`

Same errror if i use pip3 unstead pip

Clone repo and install manually - works fine

**Comment by urtow** [comment]
Catch pull request to fix this

**Comment by grf5** [comment]
I'm having the same issue.. python 3.5.2

Collecting robotframework-snmplibrary
  Using cached https://files.pythonhosted.org/packages/56/d0/b571e7f6af56a87c8d6533c30b3116ca6f842589daa7d62e526552dd8816/robotframework-snmplibrary-0.1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-rtzysdvo/robotframework-snmplibrary/setup.py", line 44
        print "build_libdoc requires the Robot Framework package."
                                                                 ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-rtzysdvo/robotframework-snmplibrary/

**Comment by grf5** [comment]
Cloning the repo and installing locally worked.

**Comment by hassan4854** [comment]
use this command : 
pip install git+https://github.com/kontron/robotframework-snmplibrary.git
